<?php
declare(strict_types = 1);

/** @var \Application\Certificate\BaseCertificate $certificate */
/** @var \Application\Model\Entity\PriceHistory[] $priceEntries */
?>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="<?= $this->url('home') ?>">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">Price History</li>
    </ol>
</nav>

<table class="table table-striped table-hover">
    <thead>
    <tr>
        <th>Datetime</th>
        <th>Price</th>
    </tr>
    </thead>
    <tbody>
    <?php if(empty($priceEntries)): ?>
        <tr>
            <td colspan="2" align="center">No entries</td>
        </tr>
    <?php else: ?>
        <?php foreach ($priceEntries as $priceEntry): ?>
            <tr>
                <td><?= (new \DateTimeImmutable('@' . $priceEntry->getDatetime()))->format('d.m.Y H:i:s') ?></td>
                <td><?= $priceEntry->getPrice() ?> <?= $certificate->getDisplayCurrency() ?></td>
            </tr>
        <?php endforeach ?>
    <?php endif ?>
    </tbody>
    <tfoot>
    <tr>
        <th colspan="2">Total <?= count($priceEntries) ?> entries</th>
    </tr>
    </tfoot>
</table>
